objective:
    metrics:
        -   name: Hartmann6
    outcome_constraints:
        - l2norm <= 1.25
parameters:
    x1:
        type: range
        bounds: [0.0, 1.0]
    x2:
        type: range
        bounds: [0.0, 1.0]
    x3:
        type: range
        bounds: [0.0, 1.0]
    x4:
        type: range
        bounds: [0.0, 1.0]
    x5:
        type: range
        bounds: [0.0, 1.0]
    x6:
        type: range
        bounds: [0.0, 1.0]
parameter_constraints:
    - .5*x1 + x2 <= 1.5
n_trials: 10
script_options:
    run_model: Rscript run_model_w_l2norm.R
# generation_strategy:
#     steps:
#         -   model: SOBOL
#             num_trials: 10
#         -   model: GPEI
#             num_trials: -1
