{% set n_trials = 10 %}
objective:
    metrics:
        - name: Hartmann6
parameters:
    {% for i in range(6) %}
    x{{ i }}:
        type: range
        bounds: [0, 1]
        value_type: float
    {% endfor %}
scheduler:
    n_trials: {{ n_trials }}
    global_stopping_strategy:
        type: improvement
        min_trials: {{ n_trials // 4 }}
        window_size: {{ n_trials // 4 }}
script_options:
    run_model: Rscript run_model.R
    exp_name: {{ config_dir_name }}_{{ n_trials }}_trials_w_stopping_strategy
