objective:
    metrics:
        # List all of your metrics
        -   metric: branin
            metric_type: synthetic_metric
            minimize: true

# List all parameters
parameters:
    x0:
        type: range
        bounds: [-5, 10]
        value_type: float
    x1:
        type: range
        bounds: [0, 15]
        value_type: float

# number of trials and other general run settings
n_trials: 50
scheduler:
    # Optional, this stops the optimization early if we converge to the specified condition
    global_stopping_strategy:
        type: improvement
        min_trials: 10
        window_size: 10
        # (This is the default) 10% improvement as a fraction of the
        # interquartile range (IQR) of the objective values seen so far.
        improvement_bar: 0.1

# Which script to run and what to write files out as
script_options:
    run_model: Rscript run_model.R
