version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - Rscript install_github_r_deps.R
      - conda list

conda:
  environment: docs/environment_docs.yml

#sphinx:
#  fail_on_warning: true
