name: boa
channels:
- pytorch
- conda-forge
dependencies:
- python=3.10
- boa-framework==0.10.0

# Aux Languages
- r
- r-jsonlite
- r-base<4.3.1
- r-devtools
- r-data.table
- r-here
#############################
# Install SWAT dependencies #
#   Windows and Linux Only  #
#############################
  # when environment is solved, enter R terminal and run::
  # devtools::install_github("chrisschuerz/SWATdata")
  # devtools::install_github("chrisschuerz/SWATrunR")
  # from inside swat folder run::
  # Rsript setup.R
