{% set n_dim_per_domain = 25 %}
{% set init_trials = 10 %}
{% set n_trials = init_trials + 40 %}

objective:
    metrics:
        # List all of your metrics here,
        # only list 1 metric for a single objective optimization
        -   metric: branin
            metric_type: synthetic_metric
            noise_sd: 0.0
            param_names: ["x2", "x{{ n_dim_per_domain + 2 }}"]
            minimize: true

parameters:
    {% for i in range(n_dim_per_domain) %}
    x{{ i }}:
        type: range
        bounds: [-5, 10]
        value_type: float
    {% endfor %}
    {% for i in range(n_dim_per_domain) %}
    x{{ i + n_dim_per_domain }}:
        type: range
        bounds: [0, 15]
        value_type: float
    {% endfor %}

scheduler:
    n_trials: {{ n_trials }}

generation_strategy:
    use_saasbo: true
    num_initialization_trials: {{ init_trials }}

script_options:
    run_model: Rscript run_model.R
