objective:
    metrics:
        - name: flo_out
parameters:
    lat_ttime:
        type: range
        bounds: [0, 10]
        value_type: float
    epco:
        type: range
        bounds: [0, 1]
        value_type: float
    esco:
        type: range
        bounds: [0, 1]
        value_type: float
    alpha:
        type: range
        bounds: [0, 1]
        value_type: float
scheduler:
    n_trials: 15
script_options:
    run_model: Rscript run_model.R
    exp_name: swat_plus_demo
